{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "limesurvey.fullname" . }}-mariadb
spec:
  type: ClusterIP
  selector:
    app: {{ include "limesurvey.fullname" . }}-mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
{{- end }}
