{{- if .Values.secret.create }}
{{- $name := .Values.mariadb.existingSecret -}}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
type: Opaque
stringData:
  {{- /* Preserve existing password on upgrade; else generate or use provided */}}
  {{- if $existing }}
  DB_PASSWORD: {{ (b64dec (index $existing.data "DB_PASSWORD")) | quote }}
  {{- else }}
  DB_PASSWORD: {{ default (randAlphaNum 24) .Values.secret.DB_PASSWORD | quote }}
  {{- end }}
  {{- /* Admin password: preserve if exists, else generate or use provided */}}
  {{- if $existing }}
  ADMIN_PASSWORD: {{ (b64dec (index $existing.data "ADMIN_PASSWORD")) | quote }}
  {{- else }}
  ADMIN_PASSWORD: {{ default (randAlphaNum 24) .Values.secret.ADMIN_PASSWORD | quote }}
  {{- end }}
{{- end }}
