name: Build and Push LimeSurvey Images

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-publish.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-publish.yaml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to push (default latest)'
        required: false
        default: 'latest'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.event.inputs.tag || 'latest' }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        component: [ 'nginx', 'phpfpm' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push nginx
        if: matrix.component == 'nginx'
        uses: docker/build-push-action@v6
        id: build-nginx
        with:
          context: docker/nginx
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/nginx:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ github.repository }}/nginx:${{ github.sha }}

      - name: Sign nginx image
        if: matrix.component == 'nginx'
        env:
          DIGEST: ${{ steps.build-nginx.outputs.digest }}
          TAG_LATEST: ${{ env.REGISTRY }}/${{ github.repository }}/nginx:${{ env.TAG }}
          TAG_SHA: ${{ env.REGISTRY }}/${{ github.repository }}/nginx:${{ github.sha }}
        run: |
          cosign sign --yes ${TAG_LATEST}@${DIGEST}
          cosign sign --yes ${TAG_SHA}@${DIGEST}

      - name: Build and push php-fpm
        if: matrix.component == 'phpfpm'
        uses: docker/build-push-action@v6
        id: build-php
        with:
          context: docker/phpfpm
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/phpfpm:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ github.repository }}/phpfpm:${{ github.sha }}

      - name: Sign php-fpm image
        if: matrix.component == 'phpfpm'
        env:
          DIGEST: ${{ steps.build-php.outputs.digest }}
          TAG_LATEST: ${{ env.REGISTRY }}/${{ github.repository }}/phpfpm:${{ env.TAG }}
          TAG_SHA: ${{ env.REGISTRY }}/${{ github.repository }}/phpfpm:${{ github.sha }}
        run: |
          cosign sign --yes ${TAG_LATEST}@${DIGEST}
          cosign sign --yes ${TAG_SHA}@${DIGEST}